name: epub_view_example
description: Example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  epub_view:
    path: ../
  blurrycontainer: ^1.0.2  
  syncfusion_flutter_sliders: ^22.2.10
  flutter_xlider: ^3.5.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/
  uses-material-design: true
